# Site settings
title: "Dan Robertson"
description: "Dan Robertson's website"
url: "http://dlrobertson.com"
baseurl: ""

#  Build settings
permalink: "/blog/:categories/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num"
paginate: 3

gems:
  - jekyll-redirect-from
  - jekyll-paginate

exclude: ["slides/reveal.js/demo.html", "slides/reveal.js/index.html"]
